services:
  database:
    container_name: prueba-terracota-postgres
  database-init:
    container_name: prueba-terracota-init
  api:
    container_name: prueba-terracota-api
  web:
    container_name: prueba-terracota-web
