-- ============================================================================
--  TERRACOTA - Esquema integral PostgreSQL 14+
--  Ejecutar conectado a la base `terracota` (ver 00_CREAR_BASE.sql).
--  Es idempotente: puede volver a ejecutarse sin destruir datos existentes.
-- ============================================================================

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE SCHEMA IF NOT EXISTS terracota;
SET search_path TO terracota, public;

CREATE SEQUENCE IF NOT EXISTS folio_ticket_seq START WITH 129;

-- ---------------------------------------------------------------- catálogos
CREATE TABLE IF NOT EXISTS roles (
  id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clave varchar(30) NOT NULL UNIQUE,
  nombre varchar(60) NOT NULL,
  CONSTRAINT roles_clave_formato CHECK (clave ~ '^[a-z_]+$')
);

CREATE TABLE IF NOT EXISTS usuarios (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(120) NOT NULL,
  usuario varchar(60) NOT NULL,
  password_hash text NOT NULL,
  activo boolean NOT NULL DEFAULT true,
  eliminado boolean NOT NULL DEFAULT false,
  creado_en timestamptz NOT NULL DEFAULT now(),
  actualizado_en timestamptz NOT NULL DEFAULT now(),
  ultimo_acceso timestamptz,
  CONSTRAINT usuarios_nombre_no_vacio CHECK (btrim(nombre) <> ''),
  CONSTRAINT usuarios_usuario_no_vacio CHECK (btrim(usuario) <> '')
);

ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS ultimo_acceso timestamptz;

CREATE UNIQUE INDEX IF NOT EXISTS usuarios_usuario_lower_uq ON usuarios (lower(usuario));
CREATE INDEX IF NOT EXISTS usuarios_vigentes_idx ON usuarios (eliminado, activo);

CREATE TABLE IF NOT EXISTS usuario_roles (
  usuario_id bigint NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  rol_id smallint NOT NULL REFERENCES roles(id) ON DELETE RESTRICT,
  PRIMARY KEY (usuario_id, rol_id)
);

CREATE TABLE IF NOT EXISTS categorias (
  id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clave varchar(30) NOT NULL UNIQUE,
  nombre varchar(60) NOT NULL,
  orden smallint NOT NULL DEFAULT 0,
  activo boolean NOT NULL DEFAULT true,
  CONSTRAINT categorias_orden_valido CHECK (orden >= 0)
);

CREATE TABLE IF NOT EXISTS productos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clave varchar(60) NOT NULL UNIQUE,
  categoria_id smallint NOT NULL REFERENCES categorias(id) ON DELETE RESTRICT,
  nombre varchar(120) NOT NULL,
  descripcion varchar(250),
  precio numeric(12,2) NOT NULL,
  stock_actual integer NOT NULL DEFAULT 50,
  stock_minimo integer NOT NULL DEFAULT 15,
  disponible boolean NOT NULL DEFAULT true,
  eliminado boolean NOT NULL DEFAULT false,
  creado_en timestamptz NOT NULL DEFAULT now(),
  actualizado_en timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT productos_precio_valido CHECK (precio >= 0),
  CONSTRAINT productos_stock_actual_valido CHECK (stock_actual >= 0),
  CONSTRAINT productos_stock_minimo_valido CHECK (stock_minimo >= 0),
  CONSTRAINT productos_clave_formato CHECK (clave ~ '^[a-z0-9-]+$')
);

CREATE INDEX IF NOT EXISTS productos_categoria_idx ON productos(categoria_id);
CREATE INDEX IF NOT EXISTS productos_vigentes_idx ON productos(eliminado, disponible);

CREATE TABLE IF NOT EXISTS mesas (
  id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero smallint NOT NULL UNIQUE,
  capacidad smallint NOT NULL DEFAULT 4,
  estado varchar(20) NOT NULL DEFAULT 'DISPONIBLE',
  activa boolean NOT NULL DEFAULT true,
  actualizado_en timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT mesas_numero_valido CHECK (numero > 0),
  CONSTRAINT mesas_capacidad_valida CHECK (capacidad > 0),
  CONSTRAINT mesas_estado_valido CHECK (estado IN ('DISPONIBLE', 'OCUPADA', 'FUERA_SERVICIO'))
);

CREATE TABLE IF NOT EXISTS estados_pedido (
  clave varchar(20) PRIMARY KEY,
  nombre varchar(50) NOT NULL,
  orden smallint NOT NULL UNIQUE,
  es_final boolean NOT NULL DEFAULT false
);

-- ---------------------------------------------------------------- operación
CREATE TABLE IF NOT EXISTS pedidos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mesa_id smallint NOT NULL REFERENCES mesas(id) ON DELETE RESTRICT,
  mesero_id bigint NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  estado varchar(20) NOT NULL DEFAULT 'PENDIENTE' REFERENCES estados_pedido(clave),
  subtotal numeric(12,2) NOT NULL DEFAULT 0,
  tasa_impuesto numeric(5,4) NOT NULL DEFAULT 0.1600,
  impuesto numeric(12,2) NOT NULL DEFAULT 0,
  total numeric(12,2) NOT NULL DEFAULT 0,
  notas varchar(500),
  creado_en timestamptz NOT NULL DEFAULT now(),
  actualizado_en timestamptz NOT NULL DEFAULT now(),
  entregado_en timestamptz,
  cerrado_en timestamptz,
  actualizado_por bigint REFERENCES usuarios(id) ON DELETE SET NULL,
  version integer NOT NULL DEFAULT 1,
  CONSTRAINT pedidos_importes_validos CHECK (subtotal >= 0 AND impuesto >= 0 AND total >= 0),
  CONSTRAINT pedidos_tasa_valida CHECK (tasa_impuesto >= 0 AND tasa_impuesto <= 1),
  CONSTRAINT pedidos_version_valida CHECK (version > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS pedidos_una_mesa_activa_uq
  ON pedidos(mesa_id)
  WHERE estado IN ('PENDIENTE', 'PREPARANDO', 'LISTO', 'ENTREGADO');
CREATE INDEX IF NOT EXISTS pedidos_estado_creado_idx ON pedidos(estado, creado_en DESC);
CREATE INDEX IF NOT EXISTS pedidos_mesero_idx ON pedidos(mesero_id, creado_en DESC);
CREATE INDEX IF NOT EXISTS pedidos_mesa_idx ON pedidos(mesa_id, creado_en DESC);

CREATE TABLE IF NOT EXISTS pedido_detalles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id bigint NOT NULL REFERENCES pedidos(id) ON DELETE CASCADE,
  producto_id bigint NOT NULL REFERENCES productos(id) ON DELETE RESTRICT,
  nombre_producto varchar(120) NOT NULL,
  cantidad integer NOT NULL,
  precio_unitario numeric(12,2) NOT NULL,
  observacion varchar(250),
  importe numeric(12,2) GENERATED ALWAYS AS (cantidad * precio_unitario) STORED,
  CONSTRAINT pedido_detalles_cantidad_valida CHECK (cantidad BETWEEN 1 AND 99),
  CONSTRAINT pedido_detalles_precio_valido CHECK (precio_unitario >= 0)
);

CREATE INDEX IF NOT EXISTS pedido_detalles_pedido_idx ON pedido_detalles(pedido_id);
CREATE INDEX IF NOT EXISTS pedido_detalles_producto_idx ON pedido_detalles(producto_id);

CREATE TABLE IF NOT EXISTS pedido_estados_historial (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id bigint NOT NULL REFERENCES pedidos(id) ON DELETE CASCADE,
  estado_anterior varchar(20) REFERENCES estados_pedido(clave),
  estado_nuevo varchar(20) NOT NULL REFERENCES estados_pedido(clave),
  usuario_id bigint REFERENCES usuarios(id) ON DELETE SET NULL,
  comentario varchar(250),
  creado_en timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS pedido_historial_pedido_idx
  ON pedido_estados_historial(pedido_id, creado_en);

CREATE TABLE IF NOT EXISTS metodos_pago (
  clave varchar(20) PRIMARY KEY,
  nombre varchar(50) NOT NULL,
  activo boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS pagos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id bigint NOT NULL UNIQUE REFERENCES pedidos(id) ON DELETE RESTRICT,
  cajero_id bigint NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  metodo varchar(20) NOT NULL REFERENCES metodos_pago(clave),
  total numeric(12,2) NOT NULL,
  monto_recibido numeric(12,2) NOT NULL,
  cambio numeric(12,2) NOT NULL DEFAULT 0,
  referencia varchar(100),
  creado_en timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT pagos_importes_validos CHECK (
    total > 0 AND monto_recibido >= total AND cambio >= 0
  )
);

CREATE INDEX IF NOT EXISTS pagos_creado_idx ON pagos(creado_en DESC);
CREATE INDEX IF NOT EXISTS pagos_metodo_idx ON pagos(metodo, creado_en DESC);

CREATE TABLE IF NOT EXISTS tickets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pago_id bigint NOT NULL UNIQUE REFERENCES pagos(id) ON DELETE RESTRICT,
  folio varchar(12) NOT NULL UNIQUE DEFAULT lpad(nextval('terracota.folio_ticket_seq')::text, 6, '0'),
  emitido_en timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS gastos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  concepto varchar(150) NOT NULL,
  monto numeric(12,2) NOT NULL,
  fecha date NOT NULL DEFAULT (now() AT TIME ZONE 'America/Mexico_City')::date,
  registrado_por bigint REFERENCES usuarios(id) ON DELETE SET NULL,
  creado_en timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT gastos_monto_valido CHECK (monto >= 0),
  CONSTRAINT gastos_concepto_no_vacio CHECK (btrim(concepto) <> '')
);

ALTER TABLE gastos ADD COLUMN IF NOT EXISTS registrado_por bigint REFERENCES usuarios(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS gastos_fecha_idx ON gastos(fecha DESC);

CREATE TABLE IF NOT EXISTS auditoria (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tabla varchar(80) NOT NULL,
  registro_id bigint,
  accion varchar(10) NOT NULL,
  usuario_bd text NOT NULL DEFAULT current_user,
  datos_anteriores jsonb,
  datos_nuevos jsonb,
  creado_en timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT auditoria_accion_valida CHECK (accion IN ('INSERT', 'UPDATE', 'DELETE'))
);

CREATE INDEX IF NOT EXISTS auditoria_tabla_registro_idx
  ON auditoria(tabla, registro_id, creado_en DESC);

-- ---------------------------------------------------------------- funciones de trigger
-- Todas fijan `search_path`: los triggers también se disparan desde sentencias
-- sueltas de la API (que se conecta con el search_path por defecto), no sólo
-- desde las funciones de negocio. Sin esto, un INSERT directo en `productos`
-- fallaría con «relation "auditoria" does not exist».
CREATE OR REPLACE FUNCTION fn_actualizar_timestamp()
RETURNS trigger LANGUAGE plpgsql
SET search_path = terracota, public
AS $$
BEGIN
  NEW.actualizado_en := now();
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION fn_validar_transicion_pedido()
RETURNS trigger LANGUAGE plpgsql
SET search_path = terracota, public
AS $$
DECLARE
  transicion_valida boolean;
BEGIN
  IF NEW.estado = OLD.estado THEN
    RETURN NEW;
  END IF;

  transicion_valida := CASE OLD.estado
    WHEN 'PENDIENTE'  THEN NEW.estado IN ('PREPARANDO', 'CANCELADO')
    WHEN 'PREPARANDO' THEN NEW.estado IN ('LISTO', 'CANCELADO')
    WHEN 'LISTO'      THEN NEW.estado IN ('ENTREGADO', 'CANCELADO')
    WHEN 'ENTREGADO'  THEN NEW.estado IN ('PAGADO', 'CANCELADO')
    ELSE false
  END;

  IF NOT transicion_valida THEN
    RAISE EXCEPTION 'Transición de pedido no permitida: % -> %', OLD.estado, NEW.estado
      USING ERRCODE = 'check_violation';
  END IF;

  NEW.version := OLD.version + 1;
  IF NEW.estado = 'ENTREGADO' THEN NEW.entregado_en := now(); END IF;
  IF NEW.estado IN ('PAGADO', 'CANCELADO') THEN NEW.cerrado_en := now(); END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION fn_historial_estado_pedido()
RETURNS trigger LANGUAGE plpgsql
SET search_path = terracota, public
AS $$
BEGIN
  IF TG_OP = 'INSERT' OR NEW.estado IS DISTINCT FROM OLD.estado THEN
    INSERT INTO pedido_estados_historial (
      pedido_id, estado_anterior, estado_nuevo, usuario_id
    ) VALUES (
      NEW.id,
      CASE WHEN TG_OP = 'INSERT' THEN NULL ELSE OLD.estado END,
      NEW.estado,
      NEW.actualizado_por
    );
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION fn_sincronizar_estado_mesa()
RETURNS trigger LANGUAGE plpgsql
SET search_path = terracota, public
AS $$
DECLARE
  mesa_anterior smallint;
  mesa_actual smallint;
BEGIN
  mesa_anterior := CASE WHEN TG_OP IN ('UPDATE', 'DELETE') THEN OLD.mesa_id END;
  mesa_actual   := CASE WHEN TG_OP IN ('INSERT', 'UPDATE') THEN NEW.mesa_id END;

  IF mesa_anterior IS NOT NULL THEN
    UPDATE mesas
       SET estado = CASE WHEN EXISTS (
         SELECT 1 FROM pedidos p
          WHERE p.mesa_id = mesa_anterior
            AND p.estado IN ('PENDIENTE', 'PREPARANDO', 'LISTO', 'ENTREGADO')
       ) THEN 'OCUPADA' ELSE 'DISPONIBLE' END
     WHERE id = mesa_anterior AND estado <> 'FUERA_SERVICIO';
  END IF;

  IF mesa_actual IS NOT NULL THEN
    UPDATE mesas
       SET estado = CASE WHEN EXISTS (
         SELECT 1 FROM pedidos p
          WHERE p.mesa_id = mesa_actual
            AND p.estado IN ('PENDIENTE', 'PREPARANDO', 'LISTO', 'ENTREGADO')
       ) THEN 'OCUPADA' ELSE 'DISPONIBLE' END
     WHERE id = mesa_actual AND estado <> 'FUERA_SERVICIO';
  END IF;
  RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION fn_recalcular_totales_pedido()
RETURNS trigger LANGUAGE plpgsql
SET search_path = terracota, public
AS $$
DECLARE
  pedido_afectado bigint;
  subtotal_calculado numeric(12,2);
BEGIN
  pedido_afectado := CASE WHEN TG_OP = 'DELETE' THEN OLD.pedido_id ELSE NEW.pedido_id END;
  SELECT COALESCE(sum(importe), 0) INTO subtotal_calculado
    FROM pedido_detalles WHERE pedido_id = pedido_afectado;

  UPDATE pedidos
     SET subtotal = subtotal_calculado,
         impuesto = round(subtotal_calculado * tasa_impuesto, 2),
         total    = subtotal_calculado + round(subtotal_calculado * tasa_impuesto, 2)
   WHERE id = pedido_afectado;

  IF TG_OP = 'UPDATE' AND OLD.pedido_id <> NEW.pedido_id THEN
    SELECT COALESCE(sum(importe), 0) INTO subtotal_calculado
      FROM pedido_detalles WHERE pedido_id = OLD.pedido_id;
    UPDATE pedidos
       SET subtotal = subtotal_calculado,
           impuesto = round(subtotal_calculado * tasa_impuesto, 2),
           total    = subtotal_calculado + round(subtotal_calculado * tasa_impuesto, 2)
     WHERE id = OLD.pedido_id;
  END IF;
  RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION fn_auditar()
RETURNS trigger LANGUAGE plpgsql
SET search_path = terracota, public
AS $$
DECLARE
  id_registro bigint;
BEGIN
  id_registro := CASE
    WHEN TG_OP = 'DELETE' THEN (to_jsonb(OLD)->>'id')::bigint
    ELSE (to_jsonb(NEW)->>'id')::bigint
  END;
  INSERT INTO auditoria(tabla, registro_id, accion, datos_anteriores, datos_nuevos)
  VALUES (
    TG_TABLE_SCHEMA || '.' || TG_TABLE_NAME,
    id_registro,
    TG_OP,
    CASE WHEN TG_OP IN ('UPDATE', 'DELETE') THEN to_jsonb(OLD) END,
    CASE WHEN TG_OP IN ('INSERT', 'UPDATE') THEN to_jsonb(NEW) END
  );
  RETURN NULL;
END;
$$;

-- ---------------------------------------------------------------- triggers
DROP TRIGGER IF EXISTS usuarios_actualizado_en_trg ON usuarios;
CREATE TRIGGER usuarios_actualizado_en_trg BEFORE UPDATE ON usuarios
FOR EACH ROW EXECUTE FUNCTION fn_actualizar_timestamp();

DROP TRIGGER IF EXISTS productos_actualizado_en_trg ON productos;
CREATE TRIGGER productos_actualizado_en_trg BEFORE UPDATE ON productos
FOR EACH ROW EXECUTE FUNCTION fn_actualizar_timestamp();

DROP TRIGGER IF EXISTS mesas_actualizado_en_trg ON mesas;
CREATE TRIGGER mesas_actualizado_en_trg BEFORE UPDATE ON mesas
FOR EACH ROW EXECUTE FUNCTION fn_actualizar_timestamp();

DROP TRIGGER IF EXISTS pedidos_validar_transicion_trg ON pedidos;
CREATE TRIGGER pedidos_validar_transicion_trg BEFORE UPDATE OF estado ON pedidos
FOR EACH ROW EXECUTE FUNCTION fn_validar_transicion_pedido();

DROP TRIGGER IF EXISTS pedidos_actualizado_en_trg ON pedidos;
CREATE TRIGGER pedidos_actualizado_en_trg BEFORE UPDATE ON pedidos
FOR EACH ROW EXECUTE FUNCTION fn_actualizar_timestamp();

DROP TRIGGER IF EXISTS pedidos_historial_trg ON pedidos;
CREATE TRIGGER pedidos_historial_trg AFTER INSERT OR UPDATE OF estado ON pedidos
FOR EACH ROW EXECUTE FUNCTION fn_historial_estado_pedido();

DROP TRIGGER IF EXISTS pedidos_sincronizar_mesa_trg ON pedidos;
CREATE TRIGGER pedidos_sincronizar_mesa_trg AFTER INSERT OR UPDATE OF estado, mesa_id OR DELETE ON pedidos
FOR EACH ROW EXECUTE FUNCTION fn_sincronizar_estado_mesa();

DROP TRIGGER IF EXISTS pedido_detalles_totales_trg ON pedido_detalles;
CREATE TRIGGER pedido_detalles_totales_trg
AFTER INSERT OR UPDATE OR DELETE ON pedido_detalles
FOR EACH ROW EXECUTE FUNCTION fn_recalcular_totales_pedido();

DROP TRIGGER IF EXISTS productos_auditoria_trg ON productos;
CREATE TRIGGER productos_auditoria_trg AFTER INSERT OR UPDATE OR DELETE ON productos
FOR EACH ROW EXECUTE FUNCTION fn_auditar();

DROP TRIGGER IF EXISTS pagos_auditoria_trg ON pagos;
CREATE TRIGGER pagos_auditoria_trg AFTER INSERT OR UPDATE OR DELETE ON pagos
FOR EACH ROW EXECUTE FUNCTION fn_auditar();

DROP TRIGGER IF EXISTS usuarios_auditoria_trg ON usuarios;
CREATE TRIGGER usuarios_auditoria_trg AFTER INSERT OR UPDATE OR DELETE ON usuarios
FOR EACH ROW EXECUTE FUNCTION fn_auditar();

-- ---------------------------------------------------------------- catálogos base
INSERT INTO roles(clave, nombre) VALUES
  ('mesero', 'Mesero'), ('caja', 'Caja'), ('cocina', 'Cocina'), ('administrador', 'Administrador')
ON CONFLICT (clave) DO UPDATE SET nombre = EXCLUDED.nombre;

INSERT INTO estados_pedido(clave, nombre, orden, es_final) VALUES
  ('PENDIENTE', 'Pendiente', 1, false),
  ('PREPARANDO', 'Preparando', 2, false),
  ('LISTO', 'Listo para entregar', 3, false),
  ('ENTREGADO', 'Entregado', 4, false),
  ('PAGADO', 'Pagado', 5, true),
  ('CANCELADO', 'Cancelado', 6, true)
ON CONFLICT (clave) DO UPDATE
SET nombre = EXCLUDED.nombre, orden = EXCLUDED.orden, es_final = EXCLUDED.es_final;

INSERT INTO metodos_pago(clave, nombre) VALUES
  ('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia')
ON CONFLICT (clave) DO UPDATE SET nombre = EXCLUDED.nombre, activo = true;

INSERT INTO categorias(clave, nombre, orden) VALUES
  ('BEBIDAS', 'Bebidas', 1), ('POSTRES', 'Postres', 2),
  ('ALIMENTOS', 'Alimentos', 3), ('PROMOS', 'Promociones', 4)
ON CONFLICT (clave) DO UPDATE SET nombre = EXCLUDED.nombre, orden = EXCLUDED.orden;

INSERT INTO mesas(numero, capacidad)
SELECT n, 4 FROM generate_series(1, 8) AS n
ON CONFLICT (numero) DO NOTHING;

-- Productos de arranque. Sólo se insertan si no existen: nunca pisan precios
-- ni stock que el usuario haya modificado desde la web o la app.
INSERT INTO productos(clave, categoria_id, nombre, descripcion, precio, stock_actual, stock_minimo)
SELECT d.clave, c.id, d.nombre, d.descripcion, d.precio, d.stock, d.minimo
FROM (VALUES
  ('cafe-americano',   'BEBIDAS',   'Café Americano',       'Grano de altura, 12 oz',      35.00::numeric, 80, 20),
  ('capuchino',        'BEBIDAS',   'Capuchino',            'Espuma de leche entera',      52.00::numeric, 70, 20),
  ('moka-frappe',      'BEBIDAS',   'Moka Frappé',          'Con leche deslactosada',      55.00::numeric, 60, 15),
  ('frappe-chai',      'BEBIDAS',   'Frappé Chai',          'Especias de la casa',         55.00::numeric, 50, 15),
  ('brownie-cacao',    'POSTRES',   'Brownie de Cacao',     'Servido caliente',            65.00::numeric, 40, 10),
  ('pastel-chocolate', 'POSTRES',   'Pastel de Chocolate',  'Rebanada individual',         58.00::numeric, 35, 10),
  ('panini-terracota', 'ALIMENTOS', 'Panini Terracota',     'Pan artesanal y pesto',       89.00::numeric, 45, 12),
  ('ensalada-casa',    'ALIMENTOS', 'Ensalada de la Casa',  'Mezcla verde y vinagreta',    96.00::numeric, 30, 10),
  ('sandwich-pavo',    'ALIMENTOS', 'Sándwich de Pavo',     'Con queso manchego',          85.00::numeric, 40, 12),
  ('combo-moka',       'PROMOS',    'Combo Moka + Postre',  'Bebida grande más postre',   100.00::numeric, 25,  8)
) AS d(clave, categoria_clave, nombre, descripcion, precio, stock, minimo)
JOIN categorias c ON c.clave = d.categoria_clave
WHERE NOT EXISTS (SELECT 1 FROM productos p WHERE p.clave = d.clave);

-- ---------------------------------------------------------------- usuarios demo
-- Las contraseñas coinciden EXACTAMENTE con CREDENCIALES.md.
-- Se guardan como hash bcrypt (pgcrypto); nunca en texto plano.
INSERT INTO usuarios(nombre, usuario, password_hash)
SELECT d.nombre, d.usuario, crypt(d.password, gen_salt('bf'))
FROM (VALUES
  ('Administrador Terracota', 'admin',   'Admin123!'),
  ('Luis Ramírez',            'mesero',  'Mesero123!'),
  ('María Delgado',           'cocina',  'Cocina123!'),
  ('Ana Sotelo',              'caja',    'Caja123!'),
  ('Diego Fuentes',           'mesero2', 'Mesero123!'),
  ('Karla Ibarra',            'gerente', 'Gerente123!')
) AS d(nombre, usuario, password)
WHERE NOT EXISTS (SELECT 1 FROM usuarios u WHERE lower(u.usuario) = lower(d.usuario));

INSERT INTO usuario_roles(usuario_id, rol_id)
SELECT u.id, r.id
FROM (VALUES
  ('admin',   'administrador'),
  ('mesero',  'mesero'),
  ('cocina',  'cocina'),
  ('caja',    'caja'),
  ('mesero2', 'mesero'),
  ('gerente', 'administrador'),
  ('gerente', 'caja')          -- usuario multi-rol para pruebas
) AS a(usuario, rol)
JOIN usuarios u ON lower(u.usuario) = a.usuario
JOIN roles r ON r.clave = a.rol
ON CONFLICT DO NOTHING;

-- Gastos de ejemplo para la gráfica del panel web (sólo si la tabla está vacía).
INSERT INTO gastos (concepto, monto, fecha)
SELECT concepto, monto, fecha
FROM (VALUES
  ('Compra de café en grano y leche',            1200.00::numeric, (now() - interval '6 days')::date),
  ('Vasos compostables y servilletas',            450.00::numeric, (now() - interval '5 days')::date),
  ('Pago de luz y servicios del local',          2300.00::numeric, (now() - interval '4 days')::date),
  ('Insumos de panadería y repostería',           850.00::numeric, (now() - interval '3 days')::date),
  ('Frutas y verduras frescas',                   320.00::numeric, (now() - interval '2 days')::date),
  ('Insumos de limpieza',                         250.00::numeric, (now() - interval '1 day')::date),
  ('Gas e insumos de cocina',                    1100.00::numeric, (now())::date)
) AS d(concepto, monto, fecha)
WHERE NOT EXISTS (SELECT 1 FROM gastos);

-- ---------------------------------------------------------------- funciones de negocio
CREATE OR REPLACE FUNCTION autenticar_usuario(p_usuario text, p_password text)
RETURNS TABLE(usuario_id bigint, nombre varchar, usuario varchar, roles text[])
LANGUAGE plpgsql
SET search_path = terracota, public
AS $$
DECLARE
  encontrado record;
BEGIN
  SELECT u.id, u.nombre, u.usuario,
         COALESCE(array_agg(r.clave ORDER BY r.clave)
           FILTER (WHERE r.clave IS NOT NULL), ARRAY[]::text[]) AS roles
    INTO encontrado
  FROM usuarios u
  LEFT JOIN usuario_roles ur ON ur.usuario_id = u.id
  LEFT JOIN roles r ON r.id = ur.rol_id
  WHERE u.activo AND NOT u.eliminado
    AND lower(u.usuario) = lower(btrim(p_usuario))
    AND u.password_hash = crypt(p_password, u.password_hash)
  GROUP BY u.id, u.nombre, u.usuario;

  IF NOT FOUND THEN
    RETURN;
  END IF;

  UPDATE usuarios SET ultimo_acceso = now() WHERE id = encontrado.id;

  usuario_id := encontrado.id;
  nombre     := encontrado.nombre;
  usuario    := encontrado.usuario;
  roles      := encontrado.roles;
  RETURN NEXT;
END;
$$;

DROP FUNCTION IF EXISTS crear_pedido(smallint, bigint, jsonb, varchar, numeric);
CREATE OR REPLACE FUNCTION crear_pedido(
  p_numero_mesa integer,
  p_mesero_id bigint,
  p_items jsonb,
  p_notas varchar DEFAULT NULL,
  p_tasa_impuesto numeric DEFAULT 0.1600
)
RETURNS pedidos
LANGUAGE plpgsql
SET search_path = terracota, public
AS $$
DECLARE
  mesa_registro mesas%ROWTYPE;
  pedido_nuevo pedidos%ROWTYPE;
  faltante record;
BEGIN
  IF jsonb_typeof(p_items) <> 'array' OR jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION 'El pedido debe contener al menos un producto.' USING ERRCODE = 'check_violation';
  END IF;

  IF p_tasa_impuesto < 0 OR p_tasa_impuesto > 1 THEN
    RAISE EXCEPTION 'La tasa de impuesto no es válida.' USING ERRCODE = 'check_violation';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM usuarios u
    JOIN usuario_roles ur ON ur.usuario_id = u.id
    JOIN roles r ON r.id = ur.rol_id
    WHERE u.id = p_mesero_id AND u.activo AND NOT u.eliminado
      AND r.clave IN ('mesero', 'administrador')
  ) THEN
    RAISE EXCEPTION 'El usuario no tiene permisos de mesero.' USING ERRCODE = 'insufficient_privilege';
  END IF;

  -- Formato de los renglones
  IF EXISTS (
    SELECT 1 FROM jsonb_array_elements(p_items) item
    WHERE NOT (item ? 'producto_clave')
       OR NOT (item ? 'cantidad')
       OR COALESCE(item->>'cantidad', '') !~ '^[1-9][0-9]*$'
       OR (item->>'cantidad')::integer > 99
  ) THEN
    RAISE EXCEPTION 'Uno o más productos tienen un formato inválido.' USING ERRCODE = 'invalid_parameter_value';
  END IF;

  -- Mesa disponible (bloqueada hasta el fin de la transacción)
  SELECT * INTO mesa_registro FROM mesas
  WHERE numero = p_numero_mesa AND activa
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'La mesa % no existe o está inactiva.', p_numero_mesa
      USING ERRCODE = 'invalid_parameter_value';
  END IF;
  IF mesa_registro.estado <> 'DISPONIBLE' THEN
    RAISE EXCEPTION 'La mesa % ya tiene un pedido activo.', p_numero_mesa
      USING ERRCODE = 'unique_violation';
  END IF;

  -- Se bloquean los productos ANTES de validar el stock: evita que dos meseros
  -- consuman las mismas existencias al mismo tiempo.
  PERFORM 1
  FROM productos p
  WHERE p.clave IN (SELECT item->>'producto_clave' FROM jsonb_array_elements(p_items) item)
  ORDER BY p.id
  FOR UPDATE;

  IF EXISTS (
    SELECT 1 FROM jsonb_array_elements(p_items) item
    LEFT JOIN productos p
      ON p.clave = item->>'producto_clave' AND p.disponible AND NOT p.eliminado
    WHERE p.id IS NULL
  ) THEN
    RAISE EXCEPTION 'Uno o más productos no existen o no están disponibles.'
      USING ERRCODE = 'invalid_parameter_value';
  END IF;

  -- Stock suficiente (agrupado: el mismo producto puede venir en varios renglones)
  SELECT p.nombre, p.stock_actual, sub.cantidad INTO faltante
  FROM (
    SELECT item->>'producto_clave' AS clave, sum((item->>'cantidad')::integer) AS cantidad
    FROM jsonb_array_elements(p_items) item
    GROUP BY 1
  ) sub
  JOIN productos p ON p.clave = sub.clave
  WHERE p.stock_actual < sub.cantidad
  LIMIT 1;

  IF FOUND THEN
    RAISE EXCEPTION 'Stock insuficiente de "%": quedan % y se pidieron %.',
      faltante.nombre, faltante.stock_actual, faltante.cantidad
      USING ERRCODE = 'check_violation';
  END IF;

  INSERT INTO pedidos(mesa_id, mesero_id, tasa_impuesto, notas, actualizado_por)
  VALUES (mesa_registro.id, p_mesero_id, p_tasa_impuesto, NULLIF(btrim(p_notas), ''), p_mesero_id)
  RETURNING * INTO pedido_nuevo;

  INSERT INTO pedido_detalles(
    pedido_id, producto_id, nombre_producto, cantidad, precio_unitario, observacion
  )
  SELECT pedido_nuevo.id, p.id, p.nombre, (item->>'cantidad')::integer, p.precio,
         NULLIF(btrim(item->>'observacion'), '')
  FROM jsonb_array_elements(p_items) item
  JOIN productos p ON p.clave = item->>'producto_clave';

  UPDATE productos p
     SET stock_actual = p.stock_actual - sub.cantidad
  FROM (
    SELECT item->>'producto_clave' AS clave, sum((item->>'cantidad')::integer) AS cantidad
    FROM jsonb_array_elements(p_items) item
    GROUP BY 1
  ) sub
  WHERE p.clave = sub.clave;

  SELECT * INTO pedido_nuevo FROM pedidos WHERE id = pedido_nuevo.id;
  RETURN pedido_nuevo;
END;
$$;

CREATE OR REPLACE FUNCTION cambiar_estado_pedido(
  p_pedido_id bigint,
  p_estado varchar,
  p_usuario_id bigint,
  p_comentario varchar DEFAULT NULL
)
RETURNS pedidos
LANGUAGE plpgsql
SET search_path = terracota, public
AS $$
DECLARE
  estado_destino varchar(20) := upper(btrim(p_estado));
  estado_actual varchar(20);
  resultado pedidos%ROWTYPE;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM usuarios WHERE id = p_usuario_id AND activo AND NOT eliminado) THEN
    RAISE EXCEPTION 'Usuario inválido o inactivo.' USING ERRCODE = 'insufficient_privilege';
  END IF;

  SELECT estado INTO estado_actual FROM pedidos WHERE id = p_pedido_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'El pedido % no existe.', p_pedido_id USING ERRCODE = 'no_data_found';
  END IF;

  IF estado_actual = estado_destino THEN
    RAISE EXCEPTION 'El pedido ya se encuentra en estado %.', estado_destino
      USING ERRCODE = 'check_violation';
  END IF;

  -- Al cancelar se devuelven las existencias al inventario.
  --
  -- Se agrupa por producto ANTES de sumar: en `UPDATE ... FROM`, si la tabla
  -- de origen tiene varias filas que casan con la misma fila destino,
  -- PostgreSQL aplica UNA sola y descarta el resto. Un pedido puede traer el
  -- mismo producto en dos renglones (por ejemplo con observaciones distintas),
  -- y sin agrupar se devolvería sólo uno de ellos: el inventario quedaría corto.
  IF estado_destino = 'CANCELADO' THEN
    UPDATE productos p
       SET stock_actual = p.stock_actual + sub.cantidad
    FROM (
      SELECT producto_id, sum(cantidad) AS cantidad
        FROM pedido_detalles
       WHERE pedido_id = p_pedido_id
       GROUP BY producto_id
    ) sub
    WHERE p.id = sub.producto_id;
  END IF;

  UPDATE pedidos
     SET estado = estado_destino, actualizado_por = p_usuario_id
   WHERE id = p_pedido_id
  RETURNING * INTO resultado;

  -- El trigger de historial ya insertó el renglón del cambio: se le adjunta el
  -- comentario. Sólo se toca ese renglón, nunca uno anterior.
  IF NULLIF(btrim(p_comentario), '') IS NOT NULL THEN
    UPDATE pedido_estados_historial
       SET comentario = left(btrim(p_comentario), 250)
     WHERE id = (
       SELECT id FROM pedido_estados_historial
       WHERE pedido_id = p_pedido_id AND estado_nuevo = estado_destino
       ORDER BY id DESC LIMIT 1
     );
  END IF;

  RETURN resultado;
END;
$$;

CREATE OR REPLACE FUNCTION registrar_pago(
  p_pedido_id bigint,
  p_cajero_id bigint,
  p_metodo varchar,
  p_monto_recibido numeric DEFAULT NULL,
  p_referencia varchar DEFAULT NULL
)
RETURNS TABLE(ticket_id bigint, folio varchar, total numeric, cambio numeric)
LANGUAGE plpgsql
SET search_path = terracota, public
AS $$
DECLARE
  pedido_registro pedidos%ROWTYPE;
  pago_id_nuevo bigint;
  ticket_id_nuevo bigint;
  folio_nuevo varchar(12);
  metodo_normalizado varchar(20) := upper(btrim(p_metodo));
  recibido numeric(12,2);
  cambio_calculado numeric(12,2);
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM usuarios u
    JOIN usuario_roles ur ON ur.usuario_id = u.id
    JOIN roles r ON r.id = ur.rol_id
    WHERE u.id = p_cajero_id AND u.activo AND NOT u.eliminado
      AND r.clave IN ('caja', 'administrador')
  ) THEN
    RAISE EXCEPTION 'El usuario no tiene permisos de caja.' USING ERRCODE = 'insufficient_privilege';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM metodos_pago WHERE clave = metodo_normalizado AND activo) THEN
    RAISE EXCEPTION 'Método de pago inválido.' USING ERRCODE = 'invalid_parameter_value';
  END IF;

  SELECT * INTO pedido_registro FROM pedidos WHERE id = p_pedido_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'El pedido % no existe.', p_pedido_id USING ERRCODE = 'no_data_found';
  END IF;
  IF pedido_registro.estado <> 'ENTREGADO' THEN
    RAISE EXCEPTION 'El pedido debe estar ENTREGADO antes de cobrar. Estado actual: %.',
      pedido_registro.estado USING ERRCODE = 'check_violation';
  END IF;
  IF pedido_registro.total <= 0 THEN
    RAISE EXCEPTION 'El pedido no tiene un total válido.' USING ERRCODE = 'check_violation';
  END IF;

  recibido := COALESCE(p_monto_recibido, pedido_registro.total);
  IF recibido < pedido_registro.total THEN
    RAISE EXCEPTION 'El monto recibido es insuficiente: faltan %.',
      to_char(pedido_registro.total - recibido, 'FM999999990.00')
      USING ERRCODE = 'check_violation';
  END IF;

  cambio_calculado := CASE
    WHEN metodo_normalizado = 'EFECTIVO' THEN recibido - pedido_registro.total
    ELSE 0
  END;

  INSERT INTO pagos(pedido_id, cajero_id, metodo, total, monto_recibido, cambio, referencia)
  VALUES (
    pedido_registro.id, p_cajero_id, metodo_normalizado, pedido_registro.total,
    CASE WHEN metodo_normalizado = 'EFECTIVO' THEN recibido ELSE pedido_registro.total END,
    cambio_calculado, NULLIF(btrim(p_referencia), '')
  ) RETURNING id INTO pago_id_nuevo;

  INSERT INTO tickets(pago_id) VALUES (pago_id_nuevo)
  RETURNING id, tickets.folio INTO ticket_id_nuevo, folio_nuevo;

  UPDATE pedidos SET estado = 'PAGADO', actualizado_por = p_cajero_id
  WHERE id = pedido_registro.id;

  RETURN QUERY SELECT ticket_id_nuevo, folio_nuevo, pedido_registro.total, cambio_calculado;
END;
$$;

-- ---------------------------------------------------------------- vistas
CREATE OR REPLACE VIEW vista_pedidos_operativos AS
SELECT
  p.id,
  m.numero AS mesa,
  p.mesero_id,
  u.nombre AS mesero,
  p.estado,
  p.subtotal,
  p.impuesto,
  p.total,
  p.notas,
  p.creado_en,
  p.entregado_en,
  COALESCE(sum(pd.cantidad), 0)::integer AS cantidad_productos,
  COALESCE(
    jsonb_agg(jsonb_build_object(
      'producto_id', pd.producto_id,
      'nombre', pd.nombre_producto,
      'cantidad', pd.cantidad,
      'precio', pd.precio_unitario,
      'importe', pd.importe,
      'observacion', pd.observacion
    ) ORDER BY pd.id) FILTER (WHERE pd.id IS NOT NULL),
    '[]'::jsonb
  ) AS items
FROM pedidos p
JOIN mesas m ON m.id = p.mesa_id
JOIN usuarios u ON u.id = p.mesero_id
LEFT JOIN pedido_detalles pd ON pd.pedido_id = p.id
GROUP BY p.id, m.numero, u.nombre;

CREATE OR REPLACE VIEW vista_tickets AS
SELECT
  t.id,
  t.folio,
  t.emitido_en,
  p.id AS pedido_id,
  m.numero AS mesa,
  pg.metodo,
  pg.total,
  pg.monto_recibido,
  pg.cambio,
  c.nombre AS cajero,
  COALESCE(
    jsonb_agg(jsonb_build_object(
      'nombre', pd.nombre_producto,
      'cantidad', pd.cantidad,
      'precio', pd.precio_unitario,
      'importe', pd.importe
    ) ORDER BY pd.id) FILTER (WHERE pd.id IS NOT NULL),
    '[]'::jsonb
  ) AS items
FROM tickets t
JOIN pagos pg ON pg.id = t.pago_id
JOIN pedidos p ON p.id = pg.pedido_id
JOIN mesas m ON m.id = p.mesa_id
JOIN usuarios c ON c.id = pg.cajero_id
LEFT JOIN pedido_detalles pd ON pd.pedido_id = p.id
GROUP BY t.id, p.id, m.numero, pg.id, c.nombre;

CREATE OR REPLACE VIEW vista_ventas_diarias AS
SELECT
  (pg.creado_en AT TIME ZONE 'America/Mexico_City')::date AS fecha,
  count(*)::integer AS pagos,
  sum(pg.total)::numeric(14,2) AS total,
  COALESCE(sum(pg.total) FILTER (WHERE pg.metodo = 'EFECTIVO'), 0)::numeric(14,2) AS efectivo,
  COALESCE(sum(pg.total) FILTER (WHERE pg.metodo = 'TARJETA'), 0)::numeric(14,2) AS tarjeta,
  COALESCE(sum(pg.total) FILTER (WHERE pg.metodo = 'TRANSFERENCIA'), 0)::numeric(14,2) AS transferencia
FROM pagos pg
GROUP BY (pg.creado_en AT TIME ZONE 'America/Mexico_City')::date;

CREATE OR REPLACE VIEW vista_inventario AS
SELECT
  p.id,
  p.clave,
  p.nombre,
  p.descripcion,
  c.clave AS categoria_clave,
  c.nombre AS categoria,
  p.precio,
  p.stock_actual,
  p.stock_minimo,
  p.disponible,
  p.eliminado,
  CASE
    WHEN p.eliminado THEN 'ELIMINADO'
    WHEN NOT p.disponible THEN 'NO_DISPONIBLE'
    WHEN p.stock_actual = 0 THEN 'AGOTADO'
    WHEN p.stock_actual <= p.stock_minimo THEN 'BAJO'
    ELSE 'DISPONIBLE'
  END AS estado,
  -- En cuántos pedidos sin cerrar aparece. Mientras sea mayor que cero el
  -- producto no puede darse de baja: se rompería un pedido en curso.
  (SELECT count(*)
     FROM pedido_detalles pd
     JOIN pedidos pe ON pe.id = pd.pedido_id
    WHERE pd.producto_id = p.id
      AND pe.estado IN ('PENDIENTE', 'PREPARANDO', 'LISTO', 'ENTREGADO')
  )::integer AS en_pedidos_activos
FROM productos p
JOIN categorias c ON c.id = p.categoria_id;

CREATE OR REPLACE VIEW vista_usuarios AS
SELECT
  u.id,
  u.nombre,
  u.usuario,
  u.activo,
  u.eliminado,
  u.creado_en,
  u.actualizado_en,
  u.ultimo_acceso,
  COALESCE(array_agg(r.clave ORDER BY r.clave)
    FILTER (WHERE r.clave IS NOT NULL), ARRAY[]::varchar[]) AS roles,
  COALESCE(array_agg(r.nombre ORDER BY r.clave)
    FILTER (WHERE r.nombre IS NOT NULL), ARRAY[]::varchar[]) AS roles_nombre
FROM usuarios u
LEFT JOIN usuario_roles ur ON ur.usuario_id = u.id
LEFT JOIN roles r ON r.id = ur.rol_id
GROUP BY u.id;

COMMIT;
