server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /terracota.apk {
        alias /descargas/terracota.apk;
        default_type application/vnd.android.package-archive;
        add_header Content-Disposition 'attachment; filename="Terracota.apk"';
        add_header Cache-Control "no-store";
    }

    location /_expo/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location /assets/ {
        expires 30d;
        add_header Cache-Control "public";
    }

    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;
    gzip_min_length 1024;
}
